# Generated by Django 2.0 on 2018-02-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansprechpartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateTimeField(verbose_name='date published')),
                ('Telefonnummer', models.CharField(max_length=20)),
                ('Geschlecht', models.CharField(max_length=1)),
                ('Vorname', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Infotext', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dienstdatum', models.DateTimeField(verbose_name='date published')),
                ('Einsatzbeginnzeit', models.DateTimeField(verbose_name='time published')),
                ('Telefonnummer', models.CharField(max_length=20)),
                ('Einsatzendezeit', models.DateTimeField(verbose_name='time published')),
            ],
        ),
        migrations.CreateModel(
            name='Einsatz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hilfstabelle1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hilfstabelle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hilfs_ID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Hilfstabelle1')),
            ],
        ),
        migrations.CreateModel(
            name='Hilfstabelle3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Alter', models.IntegerField()),
                ('Geschlecht', models.CharField(max_length=1)),
                ('Triagekategorie', models.IntegerField()),
                ('Diagnose', models.CharField(max_length=200)),
                ('Patient_Einsatzdatum', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Führungsqualifikation', models.CharField(max_length=50)),
                ('Bereitschaft', models.CharField(max_length=20)),
                ('Qualifikation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rettungsmittel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bezeichnung', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vorfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einsatzort', models.CharField(max_length=20)),
                ('Einsatzbeginn', models.DateTimeField(verbose_name='time published')),
                ('Einsatzende', models.DateTimeField(verbose_name='time published')),
                ('Einsatzdatum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz')),
            ],
        ),
        migrations.AddField(
            model_name='hilfstabelle3',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Patient'),
        ),
        migrations.AddField(
            model_name='hilfstabelle3',
            name='Vorfall_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Vorfall'),
        ),
        migrations.AddField(
            model_name='hilfstabelle2',
            name='Hilfs_ID3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Hilfstabelle3'),
        ),
        migrations.AddField(
            model_name='hilfstabelle1',
            name='Funkrufname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Rettungsmittel'),
        ),
        migrations.AddField(
            model_name='hilfstabelle1',
            name='Vorfall_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Vorfall'),
        ),
        migrations.AddField(
            model_name='einsatz',
            name='Personal_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Personal'),
        ),
        migrations.AddField(
            model_name='dienst',
            name='Einsatzdatum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz'),
        ),
        migrations.AddField(
            model_name='dienst',
            name='Personal_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Personal'),
        ),
        migrations.AddField(
            model_name='ansprechpartner',
            name='Einsatz_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz'),
        ),
    ]
