# Generated by Django 2.0 on 2018-03-06 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansprechpartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('Telefonnummer', models.CharField(max_length=20)),
                ('Geschlecht', models.CharField(choices=[('w', 'W'), ('m', 'M')], default='W', max_length=1)),
                ('Vorname', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Infotext', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dienstdatum', models.DateField(default=datetime.date.today, verbose_name='Dienstdatum')),
                ('Einsatzbeginnzeit', models.TimeField(verbose_name='Einsatzbeginn')),
                ('Funkrufname', models.CharField(max_length=20)),
                ('Einsatzendezeit', models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='Einsatzende')),
            ],
        ),
        migrations.CreateModel(
            name='Einsatz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einsatzdatum', models.DateField(default=datetime.date.today, verbose_name='Einsatzdatum')),
                ('Einsatzinfo', models.CharField(default='Einsatzinfo', max_length=254, verbose_name='Einsatzinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(default='Patientin', max_length=20)),
                ('Name', models.CharField(default='Musterfrau', max_length=20)),
                ('Alter', models.IntegerField(default='1')),
                ('Geschlecht', models.CharField(choices=[('w', 'W'), ('m', 'M')], default='W', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Führungsqualifikation', models.CharField(max_length=50)),
                ('Bereitschaft', models.CharField(max_length=20)),
                ('Qualifikation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rettungsmittel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bezeichnung', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vorfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einsatzdatum', models.DateField(default=datetime.date.today, verbose_name='Einsatzdatum')),
                ('Einsatzort', models.CharField(default='Heidenheim', max_length=50)),
                ('Einsatzbeginn', models.TimeField(default=datetime.datetime.now, verbose_name='Einsatzbeginn')),
                ('Einsatzende', models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='Einsatzende')),
                ('Triagekategorie', models.CharField(choices=[('leichte Verletzungen', 'LEICHTE VERLETZUNGEN'), ('mittlere Verletzungen', 'MITTLERE VERLETZUNGEN'), ('schwere Verletzungen', 'SCHWERE VERLETZUNGEN')], default='LEICHTE VERLETZUNGEN', max_length=21, verbose_name='Triagekategorie')),
                ('Dienst', models.ManyToManyField(to='index.Dienst')),
                ('Einsatz', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz')),
                ('Patient', models.ManyToManyField(blank=True, to='index.Patient')),
                ('Retter', models.ManyToManyField(to='index.Rettungsmittel')),
            ],
        ),
        migrations.AddField(
            model_name='einsatz',
            name='Personal_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Personal'),
        ),
        migrations.AddField(
            model_name='dienst',
            name='Einsatz_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='index.Einsatz'),
        ),
        migrations.AddField(
            model_name='dienst',
            name='Personal_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='index.Personal'),
        ),
        migrations.AddField(
            model_name='ansprechpartner',
            name='Einsatz_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz'),
        ),
    ]
