# Generated by Django 2.0 on 2018-02-07 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hilfstabelle2',
            name='Hilfs_ID1',
        ),
        migrations.RemoveField(
            model_name='hilfstabelle2',
            name='Hilfs_ID3',
        ),
        migrations.RemoveField(
            model_name='hilfstabelle1',
            name='Funkrufname',
        ),
        migrations.RemoveField(
            model_name='hilfstabelle3',
            name='Patient_ID',
        ),
        migrations.AddField(
            model_name='hilfstabelle1',
            name='Patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hilfstabelle3',
            name='Hilfstab1',
            field=models.ManyToManyField(to='index.Hilfstabelle1'),
        ),
        migrations.AddField(
            model_name='hilfstabelle3',
            name='Rettungsmittel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Rettungsmittel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Dienst',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Dienst'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Einsatz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Patient',
            field=models.ManyToManyField(through='index.Hilfstabelle1', to='index.Patient'),
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Retter',
            field=models.ManyToManyField(through='index.Hilfstabelle3', to='index.Rettungsmittel'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzdatum',
            field=models.DateTimeField(verbose_name='Einsatzdatum'),
        ),
        migrations.DeleteModel(
            name='Hilfstabelle2',
        ),
    ]
