# Generated by Django 2.0 on 2018-03-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansprechpartner',
            name='Datum',
        ),
        migrations.RemoveField(
            model_name='dienst',
            name='Dienstdatum',
        ),
        migrations.RemoveField(
            model_name='vorfall',
            name='Einsatzdatum',
        ),
    ]
