# Generated by Django 2.0.3 on 2018-03-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180308_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorfall',
            name='Triagekategorie',
            field=models.CharField(choices=[('geringes Risiko', 'GERINGES RISIKO'), ('mittleres Risiko', 'MITTLERES RISIKO'), ('hohes Risiko', 'HOHES RISIKO')], default='LEICHTE VERLETZUNGEN', max_length=21, verbose_name='Triagekategorie'),
        ),
    ]
