# Generated by Django 2.0 on 2018-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180207_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzort',
            field=models.CharField(default='Heidenheim', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Patient',
            field=models.ManyToManyField(default='Hansl', through='index.Hilfstabelle1', to='index.Patient'),
        ),
    ]
