# Generated by Django 2.0 on 2018-02-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180207_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienst',
            name='Dienstdatum',
            field=models.DateTimeField(default='01.01.2018', verbose_name='date published'),
        ),
    ]
