# Generated by Django 2.0.3 on 2018-03-15 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180315_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Alter',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(110)]),
        ),
    ]
