# Generated by Django 2.0 on 2018-02-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180207_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Meier', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Vorname',
            field=models.CharField(default='Herbert', max_length=20),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzdatum',
            field=models.DateTimeField(default='01.01.2018', verbose_name='Einsatzdatum'),
        ),
    ]
