# Generated by Django 2.0 on 2018-02-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180207_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilfstabelle1',
            name='Patient',
            field=models.ForeignKey(default='Patient', on_delete=django.db.models.deletion.CASCADE, to='index.Patient'),
        ),
        migrations.AlterField(
            model_name='hilfstabelle1',
            name='Vorfall_ID',
            field=models.ForeignKey(default='Vorfall', on_delete=django.db.models.deletion.CASCADE, to='index.Vorfall'),
        ),
        migrations.AlterField(
            model_name='hilfstabelle3',
            name='Rettungsmittel',
            field=models.ForeignKey(default='rettungsmitel', on_delete=django.db.models.deletion.CASCADE, to='index.Rettungsmittel'),
        ),
        migrations.AlterField(
            model_name='hilfstabelle3',
            name='Vorfall_ID',
            field=models.ForeignKey(default='Vorfall', on_delete=django.db.models.deletion.CASCADE, to='index.Vorfall'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Dienst',
            field=models.ForeignKey(default='Dienst', on_delete=django.db.models.deletion.CASCADE, to='index.Dienst'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatz',
            field=models.ForeignKey(default='Einsatz', on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz'),
        ),
    ]
