# Generated by Django 2.0 on 2018-02-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180207_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dienst',
            old_name='Einsatzdatum',
            new_name='Einsatz_ID',
        ),
        migrations.RenameField(
            model_name='hilfstabelle3',
            old_name='Hilfstab1',
            new_name='Hilfstabelle2',
        ),
        migrations.AddField(
            model_name='einsatz',
            name='Einsatzdatum',
            field=models.DateTimeField(default='2018-01-01 01:00', verbose_name='Einsatzdatum'),
        ),
        migrations.AddField(
            model_name='einsatz',
            name='Einsatzinfo',
            field=models.CharField(default='Einsatzinfo', max_length=254, verbose_name='Einsatzinfo'),
        ),
        migrations.AlterField(
            model_name='hilfstabelle1',
            name='Patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Patient'),
        ),
        migrations.AlterField(
            model_name='hilfstabelle1',
            name='Vorfall_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Vorfall'),
        ),
        migrations.AlterField(
            model_name='hilfstabelle3',
            name='Rettungsmittel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Rettungsmittel'),
        ),
        migrations.AlterField(
            model_name='hilfstabelle3',
            name='Vorfall_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Vorfall'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Dienst',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Dienst'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz'),
        ),
    ]
