# Generated by Django 2.0 on 2018-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180207_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatz',
            name='Einsatzdatum',
            field=models.DateTimeField(default='2018-01-01 01:00', verbose_name='Einsatzdatum'),
        ),
    ]
