# Generated by Django 2.0 on 2018-02-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180207_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienst',
            name='Dienstdatum',
            field=models.DateTimeField(default='2018-01-01 01:00', verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzdatum',
            field=models.DateTimeField(default='2018-01-01 01:00', verbose_name='Einsatzdatum'),
        ),
    ]
