# Generated by Django 2.0 on 2018-02-07 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20180207_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienst',
            name='Dienstdatum',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Dienstdatum'),
        ),
        migrations.AlterField(
            model_name='einsatz',
            name='Einsatzdatum',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Einsatzdatum'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzbeginn',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Einsatzbeginn'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzdatum',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Einsatzdatum'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzende',
            field=models.TimeField(verbose_name='Einsatzende'),
        ),
    ]
