# Generated by Django 2.0 on 2018-02-07 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180207_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatz',
            name='Einsatzdatum',
            field=models.DateField(default=datetime.date.today, verbose_name='Einsatzdatum'),
        ),
    ]
