# Generated by Django 2.0 on 2018-02-07 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20180207_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansprechpartner',
            name='Datum',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='dienst',
            name='Dienstdatum',
            field=models.DateField(default=datetime.date.today, verbose_name='Dienstdatum'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Patient_Einsatzdatum',
            field=models.DateField(verbose_name='Behandlungsdatum'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzdatum',
            field=models.DateField(default=datetime.date.today, verbose_name='Einsatzdatum'),
        ),
    ]
