# Generated by Django 2.0 on 2018-02-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20180208_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vorfall',
            old_name='Hilfstabelle4',
            new_name='Dienst',
        ),
    ]
