# Generated by Django 2.0 on 2018-02-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20180208_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hilfstabelle1',
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='hilfstabelle1',
            name='Vorfall_ID',
        ),
        migrations.RemoveField(
            model_name='hilfstabelle3',
            name='Hilfstabelle2',
        ),
        migrations.RemoveField(
            model_name='hilfstabelle3',
            name='Rettungsmittel',
        ),
        migrations.RemoveField(
            model_name='hilfstabelle3',
            name='Vorfall_ID',
        ),
        migrations.RemoveField(
            model_name='vorfall',
            name='Dienst',
        ),
        migrations.RemoveField(
            model_name='vorfall',
            name='Einsatz',
        ),
        migrations.RemoveField(
            model_name='vorfall',
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='vorfall',
            name='Retter',
        ),
        migrations.DeleteModel(
            name='Hilfstabelle1',
        ),
        migrations.DeleteModel(
            name='Hilfstabelle3',
        ),
        migrations.DeleteModel(
            name='Vorfall',
        ),
    ]
