# Generated by Django 2.0 on 2018-02-28 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20180208_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vorfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einsatzdatum', models.DateField(default=datetime.date.today, verbose_name='Einsatzdatum')),
                ('Einsatzort', models.CharField(default='Heidenheim', max_length=50)),
                ('Einsatzbeginn', models.TimeField(default=datetime.datetime.now, verbose_name='Einsatzbeginn')),
                ('Einsatzende', models.TimeField(verbose_name='Einsatzende')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Diagnose',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Patient_Einsatzdatum',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Triagekategorie',
        ),
        migrations.AlterField(
            model_name='ansprechpartner',
            name='Einsatz_ID',
            field=models.ForeignKey(default='Einsatz', on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz'),
        ),
        migrations.AlterField(
            model_name='dienst',
            name='Einsatz_ID',
            field=models.ForeignKey(default='Einsatz', on_delete=django.db.models.deletion.DO_NOTHING, to='index.Einsatz'),
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Dienst',
            field=models.ManyToManyField(to='index.Dienst'),
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Einsatz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz'),
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Patient',
            field=models.ManyToManyField(to='index.Patient'),
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Retter',
            field=models.ManyToManyField(to='index.Rettungsmittel'),
        ),
    ]
