# Generated by Django 2.0 on 2018-02-08 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20180208_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vorfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einsatzdatum', models.DateField(default=datetime.date.today, verbose_name='Einsatzdatum')),
                ('Einsatzort', models.CharField(default='Heidenheim', max_length=50)),
                ('Einsatzbeginn', models.TimeField(default=datetime.datetime.now, verbose_name='Einsatzbeginn')),
                ('Einsatzende', models.TimeField(verbose_name='Einsatzende')),
                ('Dienst', models.ManyToManyField(to='index.Dienst')),
                ('Einsatz', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='index.Einsatz')),
                ('Patienten', models.ManyToManyField(to='index.Patient')),
                ('Retter', models.ManyToManyField(to='index.Rettungsmittel')),
            ],
        ),
    ]
