# Generated by Django 2.0 on 2018-02-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_vorfall'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_vorfall_Patienten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='index_vorfall_Retter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorfaelle', models.ManyToManyField(to='index.index_vorfall_Patienten')),
            ],
        ),
    ]
