# Generated by Django 2.0 on 2018-02-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20180228_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='vorfall',
            name='Triagekategorie',
            field=models.IntegerField(default='1', verbose_name='Triagekategorie'),
        ),
    ]
