# Generated by Django 2.0 on 2018-02-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_vorfall_triagekategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorfall',
            name='Triagekategorie',
            field=models.CharField(choices=[('leichte Verletzungen', 'LEICHTE VERLETZUNGEN'), ('mittlere Verletzungen', 'MITTLERE VERLETZUNGEN'), ('schwere Verletzungen', 'SCHWERE VERLETZUNGEN')], max_length=21, verbose_name='Triagekategorie'),
        ),
    ]
