# Generated by Django 2.0 on 2018-02-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_index_vorfall_patienten_index_vorfall_retter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_vorfall_retter',
            name='Vorfaelle',
        ),
        migrations.DeleteModel(
            name='index_vorfall_Patienten',
        ),
        migrations.DeleteModel(
            name='index_vorfall_Retter',
        ),
    ]
