# Generated by Django 2.0 on 2018-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20180208_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Diagnose',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Patient_Einsatzdatum',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Triagekategorie',
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Diagnose',
            field=models.CharField(default='Krank', max_length=200),
        ),
        migrations.AddField(
            model_name='vorfall',
            name='Triagekategorie',
            field=models.IntegerField(default='1'),
        ),
    ]
