# Generated by Django 2.0 on 2018-02-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20180228_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='rettungsmittel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rettungsmittel',
            name='Bezeichnung',
            field=models.CharField(max_length=30),
        ),
    ]
