# Generated by Django 2.0 on 2018-02-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20180220_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behandlung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Triagekategorie', models.IntegerField(default='1')),
                ('Diagnose', models.CharField(default='Krank', max_length=200)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='vorfall',
            name='Diagnose',
        ),
        migrations.RemoveField(
            model_name='vorfall',
            name='Patienten',
        ),
        migrations.RemoveField(
            model_name='vorfall',
            name='Triagekategorie',
        ),
        migrations.AddField(
            model_name='behandlung',
            name='Vorfall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Vorfall'),
        ),
    ]
