# Generated by Django 2.0 on 2018-02-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20180220_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienst',
            name='Einsatz_ID',
            field=models.ForeignKey(default='Einsatz', on_delete=django.db.models.deletion.DO_NOTHING, to='index.Einsatz'),
        ),
    ]
