# Generated by Django 2.0.2 on 2018-03-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20180301_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienst',
            name='Einsatzendezeit',
            field=models.TimeField(blank=True, null=True, verbose_name='Einsatzende'),
        ),
    ]
