# Generated by Django 2.0.2 on 2018-03-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20180301_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienst',
            name='Einsatzendezeit',
            field=models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='Einsatzende'),
        ),
        migrations.AlterField(
            model_name='vorfall',
            name='Einsatzende',
            field=models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='Einsatzende'),
        ),
    ]
