# Generated by Django 2.0.2 on 2018-03-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20180301_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorfall',
            name='Patient',
            field=models.ManyToManyField(blank=True, to='index.Patient'),
        ),
    ]
